name: head_knocker
description: A new app for your car

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  songs_repository:
    path: packages/songs_repository
  form_inputs:
    path: packages/form_inputs
  bloc: ^8.0.0-dev.3
  flutter_bloc: ^8.0.0-dev.2
  intl: ^0.17.0
  url_launcher: ^6.0.3
  google_fonts: ^2.1.0
  flow_builder: ^0.0.4
  equatable: ^2.0.3
  formz: ^0.4.0
  very_good_analysis: ^2.0.0
  http: ^0.13.4
  just_audio: ^0.9.15
  audio_session: ^0.1.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
